# Generated by Django 6.0 on 2025-12-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('std_number', models.IntegerField()),
                ('teacher', models.CharField(choices=[('karbalaei', 'Karbalaei'), ('hasanzadeh', 'Hasanzadeh'), ('mohammadi', 'Mohammadi')], default='karbalaei', max_length=15)),
            ],
        ),
    ]
